name: update-submodule
on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
      branch:
        type: string
  repository_dispatch:
    types: [update]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  update:
    name: Update Submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      
      - name: Setup minimum typescript code runner
        run: |
          npm i -g ts-node
          npm i -D @types/node
          echo '{"compilerOptions": {"target": "ES5", "module": "CommonJS", "esModuleInterop": true, "allowSyntheticDefaultImports": true}}' > ./tsconfig.json
      
      - name: Find and update target submodule
        run: |
          npm i child_process properties-reader
          ts-node ./.github/workflows/filter-and-update-submodule.ts
          rm -rf node_modules package-lock.json package.json tsconfig.json
        env:
          REPOSITORY: ${{ github.event.client_payload.repo || github.event.inputs.repository }}
          BRANCH: ${{ github.event.client_payload.branch || github.event.inputs.branch }}
          SHA: ${{ github.event.client_payload.sha }}
          ORG_PAT: ${{ secrets.ORG_PAT }}

      - name: Commit diffs
        uses: actions-js/push@v1.4
        env:
          HEAD_SHA: ${{ env.HEAD_SHA }}
        with:
          github_token: ${{ secrets.ORG_PAT }}
          message: Update submodule ${{ github.event.client_payload.repo || github.event.inputs.repository }}@${{ env.HEAD_SHA }}
          force: true
