on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
      branch:
        type: string
  repository_dispatch:
    types: [update]
name: Update
jobs:
  update:
    name: Update Submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup minimum typescript code runner
        run: |
          npm i -g ts-node
          npm i -D @types/node
          echo '{"compilerOptions": {"target": "ES5", "module": "CommonJS", "esModuleInterop": true, "allowSyntheticDefaultImports": true}}' > ./tsconfig.json
      
      - name: Find target submodule
        run: |
          npm i child_process properties-reader
          ts-node ./.github/workflows/filter-and-update-submodule.ts
        env:
          REPOSITORY: ${{ github.event.client_payload.repo || github.event.inputs.repository }} 
          BRANCH: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Update submodule and commit diffs
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.ORG_PAT }}
          branch: main
          message: Update submodule ${{ github.event.client_payload.repo }}@${{ github.event.client_payload.sha }}
